def begin_profiling_session(filepath: str) -> None: ...
def end_profiling_session() -> None: ...
def begin_profiling_frame() -> int | None: ...
def end_profiling_frame(begin_ts: int, func_name: str, /) -> None: ...
def emit_profiling_event(name: str) -> None: ...
def update_profiling_counter(value: float, name: str) -> None: ...
def is_profiling_enabled() -> bool: ...
