DEFAULT_ICON_FILEPATH = "branding/spykeIcon.ico"

DEFAULT_IMGUI_BG_COLOR = "#c9c6c5"
DEFAULT_IMGUI_HIGLIGHT_COLOR = "black"
DEFAULT_IMGUI_FONT = ("Helvetica", 9)
DEFAULT_IMGUI_TITLE_BG_COLOR = "#8c8c8c"
