import ctypes
import psutil
import time
import os
import numpy as np
import threading
from OpenGL import GL

START_TIME = time.perf_counter()
_THREAD_SYNC = threading.Event()

DEFAULT_LOG_FILENAME = "novaDefaultLog.log"
DEFAULT_ICON_FILEPATH = "branding/spykeIcon.ico"

DEFAULT_IMGUI_BG_COLOR = "#c9c6c5"
DEFAULT_IMGUI_HIGLIGHT_COLOR = "black"
DEFAULT_IMGUI_FONT = ("Helvetica", 9)
DEFAULT_IMGUI_TITLE_BG_COLOR = "#8c8c8c"

MAX_LOADING_TASKS_COUNT = 6

DEBUG_LOG_TO_FILE = True

_MAIN_PROCESS = psutil.Process(os.getpid())

_OPENGL_VER_MAJOR = 4
_OPENGL_VER_MINOR = 5

_GL_FLOAT_SIZE = ctypes.sizeof(ctypes.c_float)
_GL_INT_SIZE = ctypes.sizeof(ctypes.c_int)

_FLOAT_SIZE = ctypes.sizeof(ctypes.c_float)
_INT_SIZE = ctypes.sizeof(ctypes.c_int)

_C_FLOAT_P = ctypes.POINTER(ctypes.c_float)
_C_INT_P = ctypes.POINTER(ctypes.c_int)

_NP_FLOAT = np.float32
_NP_DOUBLE = np.float64
_NP_BYTE = np.int8
_NP_UBYTE = np.uint8
_NP_SHORT = np.int16
_NP_USHORT = np.uint16
_NP_INT = np.int32
_NP_UINT = np.uint32
_NP_LONG = np.int64
_NP_ULONG = np.uint64

_GL_TYPE_NP_TYPE_MAP = {
	GL.GL_FLOAT: _NP_FLOAT,
	GL.GL_DOUBLE: _NP_DOUBLE,
	GL.GL_BYTE: _NP_BYTE,
	GL.GL_SHORT: _NP_SHORT,
	GL.GL_INT: _NP_INT,
	GL.GL_UNSIGNED_BYTE: _NP_UBYTE,
	GL.GL_UNSIGNED_SHORT: _NP_USHORT,
	GL.GL_UNSIGNED_INT: _NP_UINT
}

_GL_TYPE_SIZE_MAP = {
	GL.GL_DOUBLE: 8,
	GL.GL_FIXED: 4,
	GL.GL_FLOAT: 4,
	GL.GL_UNSIGNED_INT: 4,
	GL.GL_INT: 4,
	GL.GL_UNSIGNED_SHORT: 2,
	GL.GL_SHORT: 2,
	GL.GL_HALF_FLOAT: 2,
	GL.GL_UNSIGNED_BYTE: 1,
	GL.GL_BYTE: 1
}

_IMAGE_FORMAT_MAP = {
	"JPEG": GL.GL_RGB,
	"JPG": GL.GL_RGB,
	"PNG": GL.GL_RGBA,
	"RGB": GL.GL_RGB,
	"RGBA": GL.GL_RGBA
}

_GL_ERROR_CODE_NAMES_MAP = {
	GL.GL_INVALID_ENUM: "INVALID_ENUM",
	GL.GL_INVALID_VALUE: "INVALID_VALUE",
	GL.GL_INVALID_OPERATION: "INVALID_OPERATION",
	GL.GL_STACK_OVERFLOW: "STACK_OVERFLOW",
	GL.GL_STACK_UNDERFLOW: "STACK_UNDERFLOW",
	GL.GL_OUT_OF_MEMORY: "OUT_OF_MEMORY",
	GL.GL_INVALID_FRAMEBUFFER_OPERATION: "INVALID_FRAMEBUFFER_OPERATION",
	GL.GL_CONTEXT_LOST: "CONTEXT_LOST"}

_GL_FB_ERROR_CODE_NAMES_MAP = {
	GL.GL_FRAMEBUFFER_UNDEFINED: "FRAMEBUFFER_UNDEFINED",
	GL.GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: "INCOMPLETE_ATTACHMENT",
	GL.GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: "INCOMPLETE_MISSING_ATTACHMENT",
	GL.GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER: "FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
	GL.GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER: "FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
	GL.GL_FRAMEBUFFER_UNSUPPORTED: "GL_FRAMEBUFFER_UNSUPPORTED",
	GL.GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
	GL.GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS : "GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS"
}

_GL_FILL_MODE_NAMES_MAP = {
	GL.GL_FILL: "FILL",
	GL.GL_LINE: "LINE",
	GL.GL_POINT: "POINT"
}