import typing as t

class Event[T]:
    def subscribe(self,
                  callback: t.Callable[[T], t.Any],
                  /,
                  priority: int = 0,
                  should_consume: bool = False) -> None: ...
    def unsubscribe(self, callback: t.Callable[[T], t.Any], /) -> None: ...
    def invoke(self, data: T, /) -> None: ...
    def clear_handlers(self) -> None: ...
